---
published: true
author: David Wan
layout: post
title: MYSQL5.5版本复制突发失效故障深度调查
category: MYSQL
summary: MYSQL5.5版本定期出现复制失效，所有指标正常，但数据不再更新，重启后复制生效，但数据已破坏，本文就调查过程进行一次记录，就该故障的分析详细介绍一下TRACE的使用。
tags:
  - MYSQL

---


### 故障描述

```
某业务从库，读写分离，在没有任何错误日志，有关复制延时监控指标正常的背景下，从库突然不再做任何数据更新，
同时，中继日志正常向前推进，相当于所有操作失踪在黑洞中。
将主库重启后，复制操作恢复，此时往往因数据不一致而中断。
此类故障，每隔15天或1个月出现一次。

```


### 问题分析

#### 第一环节：获取DBUG内容

因为没有任何错误日志，要找到关键信息，需要使用MYSQL自带的DBUG工具，获取TRACE日志。(为分析故障，保留了现场，无业务访问)

参考：
> [MYSQL的DBUG使用方法](https://dbathread.com/2018/06/24/MYSQL%E7%9A%84DBUG%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95/)

使用debug='d:t:i:o,/tmp/mysqld.trace'获取日志。

#### 第二环节：获取复制线程的日志内容

通过在复制线程中使用的函数next_event，检查出mysqld.trace中，相应的线程号，然后过滤出有关线程的所有内容。
截取部分内容如下：

```
T@6    :  5518:       slave.cc:  2516:    2: | >exec_relay_log_event
T@6    :  5519:       slave.cc:  4573:    3: | | >next_event
T@6    :  5520:       slave.cc:   915:    4: | | | >sql_slave_killed
T@6    :  5521:       slave.cc:   994:    4: | | | <sql_slave_killed 994
T@6    :  5522:       slave.cc:  4637:    3: | | | info: my_b_tell(cur_log)=127752 rli->event_relay_log_pos=127752
T@6    :  5523:   log_event.cc:  1133:    4: | | | >Log_event::read_log_event
T@6    :  5524:   log_event.cc:  1147:    4: | | | | info: my_b_tell: 127752
T@6    :  5525:    my_malloc.c:    31:    5: | | | | >my_malloc
T@6    :  5526:    my_malloc.c:    32:    5: | | | | | my: size: 28  my_flags: 16
T@6    :  5527:    my_malloc.c:    65:    5: | | | | | exit: ptr: 0x3a2f69c0
T@6    :  5528:    my_malloc.c:    66:    5: | | | | <my_malloc 66
T@6    :  5529:   log_event.cc:  1230:    5: | | | | >Log_event::read_log_event(char*,...)
T@6    :  5530:   log_event.cc:  1232:    5: | | | | | info: binlog_version: 4
T@6    :  5531:   log_event.cc:  1233:    5: | | | | | data: Memory: 0x3a2f69c0  Bytes: (27)
T@6    :  5532:    my_malloc.c:    31:    6: | | | | | >my_malloc
T@6    :  5533:    my_malloc.c:    32:    6: | | | | | | my: size: 80  my_flags: 24
T@6    :  5534:    my_malloc.c:    65:    6: | | | | | | exit: ptr: 0x3a2ce580
T@6    :  5535:    my_malloc.c:    66:    6: | | | | | <my_malloc 66
T@6    :  5536:   log_event.cc:   805:    5: | | | | | info: log_pos: 117078642
T@6    :  5537:   log_event.cc:  1373:    5: | | | | | read_event: Xid(type_code: 16; event_len: 27)
T@6    :  5538:   log_event.cc:  1402:    5: | | | | <Log_event::read_log_event(char*,...) 1402
T@6    :  5539:   log_event.cc:  1216:    4: | | | <Log_event::read_log_event 1216
T@6    :  5540:       slave.cc:  4666:    3: | | <next_event 4666
T@6    :  5541:       slave.cc:   915:    3: | | >sql_slave_killed
T@6    :  5542:       slave.cc:   994:    3: | | <sql_slave_killed 994
T@6    :  5543:       slave.cc:  2373:    3: | | >apply_event_and_update_pos
T@6    :  5544:       slave.cc:  2377:    3: | | | exec_event: Xid(type_code: 16; server_id: 1721033306)
```

为便于理解，对以上内容略加说明:
> 第一列：T@6是编号，说明来自同一线程的DBUG内容
> 第三列：log_event.cc是代码文件
> 第四列：DBGU代码在文件中的位置
> 第五列：编号4，5，3等，代表调用深度
> 第六列：DBGU的内容，>代表进入函数，而<代表离开该函数

#### 第三环节：注入DBUG_PRINT

```
在handler.cc的1213行的ha_commit_trans函数内
ha_check_and_coalesce_trx_read_only函数返回了事务列表已经注册的引擎个数
按照业务的情况，只有binlog和innodb两个引擎，所以返回值如果为2，则正常，未验证返回值，
可以在ha_check_and_coalesce_trx_read_only调用后，增加DBUG_PRINT内容，显示返回值。
```

返回的结果如下：

```
T@6    : 16259:     handler.cc:  1258:    6: | | | | | | info: rw_ha_count : 0
```

说明在事务commit前，事务列表并未正常的注册，这证明了复制的失效，原因来自MYSQL自身，而不是磁盘等可能的外部原因。


#### 第三环节：获取正常的主从复制的日志内容

使用相同的方法，获取一个正常的复制线程的DBUG日志

#### 第四环节：比较及分析

从next_event开始，逐次比较两方的调用顺序，关注的点在，非正常的复制中，很可能因某种原因，导致了调用链的缺失，在调用链变得不一致之前最近一次调用，很可能是突破口。


首先，可以发现在table_mapping的get_table结束后，非正常复制丢失了，BINLOG事务注册部分及其他大量函数调用。
其次，可以发现，正常的复制，在get_table函数返回的时候，m_table返回了正常的TABLE_LIST结构体的内存地址

```
T@6    :  8012:  rpl_tblmap.cc:    62:    5: | | | | >table_mapping::get_table(ulong)
T@6    :  8013:  rpl_tblmap.cc:    63:    5: | | | | | enter: table_id: 2355544006
T@6    :  8014:         hash.c:   264:    6: | | | | | >my_hash_first_from_hash_value
T@6    :  8015:         hash.c:   276:    6: | | | | | | exit: found key at 0
T@6    :  8016:         hash.c:   278:    6: | | | | | <my_hash_first_from_hash_value 278
T@6    :  8017:  rpl_tblmap.cc:    69:    5: | | | | | info: tid 2355544006 -> table 0x3a30b9e0 (order_81_0)
T@6    :  8018:  rpl_tblmap.cc:    70:    5: | | | | <table_mapping::get_table(ulong) 70
T@6    :  8019:   log_event.cc:  8042:    4: | | | | debug: m_table: 0x3a30b9e0, m_table_id: 2355544006
```

而故障的复制列表中，在get_table函数返回的时候，m_table返回了0x0，并且在get_table返回前，```info: tid 4603787794 is not mapped!```

```
T@6    : 16245:  rpl_tblmap.cc:    62:    5: | | | | >table_mapping::get_table(ulong)
T@6    : 16246:  rpl_tblmap.cc:    63:    5: | | | | | enter: table_id: 4603787794
T@6    : 16247:         hash.c:   264:    6: | | | | | >my_hash_first_from_hash_value
T@6    : 16248:         hash.c:   290:    6: | | | | | <my_hash_first_from_hash_value 290
T@6    : 16249:  rpl_tblmap.cc:    73:    5: | | | | | info: tid 4603787794 is not mapped!
T@6    : 16250:  rpl_tblmap.cc:    74:    5: | | | | <table_mapping::get_table(ulong) 74
T@6    : 16251:   log_event.cc:  8042:    4: | | | | debug: m_table: 0x0, m_table_id: 4603787794
```

这是一个很好的入口！MYSQL为了处理MAP EVENT,在将每个DML，拆分为MAP EVENT和WRITES EVENT等操作性EVENT。而代码table_mapping.set_table和get_table是个关键函数，这2个函数，先行将table_id和table_list数据结构，以及表名等信息，存入列表(加入不存在的话)，在get_table中，通过table_id，将table_list的数据结构取出来。

让我们观察这一段DBUG的前面部分

正常的复制

```
T@6    :  7990:  rpl_tblmap.cc:   105:    5: | | | | >table_mapping::set_table(ulong,TABLE*)
T@6    :  7991:  rpl_tblmap.cc:   108:    5: | | | | | enter: table_id: 2355544006  table: 0x3a30b9e0 (order_81_0)
T@6    :  7992:         hash.c:   264:    6: | | | | | >my_hash_first_from_hash_value
T@6    :  7993:         hash.c:   290:    6: | | | | | <my_hash_first_from_hash_value 290
T@6    :  7994:  rpl_tblmap.cc:   136:    5: | | | | | info: tid 2355544006 -> table 0x3a30b9e0 (order_81_0)
T@6    :  7995:  rpl_tblmap.cc:   137:    5: | | | | <table_mapping::set_table(ulong,TABLE*) 137

...

T@6    :  8012:  rpl_tblmap.cc:    62:    5: | | | | >table_mapping::get_table(ulong)
T@6    :  8013:  rpl_tblmap.cc:    63:    5: | | | | | enter: table_id: 2355544006
T@6    :  8014:         hash.c:   264:    6: | | | | | >my_hash_first_from_hash_value
T@6    :  8015:         hash.c:   276:    6: | | | | | | exit: found key at 0
T@6    :  8016:         hash.c:   278:    6: | | | | | <my_hash_first_from_hash_value 278
T@6    :  8017:  rpl_tblmap.cc:    69:    5: | | | | | info: tid 2355544006 -> table 0x3a30b9e0 (order_81_0)
T@6    :  8018:  rpl_tblmap.cc:    70:    5: | | | | <table_mapping::get_table(ulong) 70
```

set_table和get_table函数，在DBUG_ENTER中，table_id是一致的。

而故障复制的日志中table_id居然不一致，根据这2个值，我们可以猜测，是否出现了int值的截断，将2个值比较，我们可以发现308820498正好等于4603787794二进制截断第33位的1.

```
T@6    : 16223:  rpl_tblmap.cc:   105:    5: | | | | >table_mapping::set_table(ulong,TABLE*)
T@6    : 16224:  rpl_tblmap.cc:   108:    5: | | | | | enter: table_id: 308820498  table: 0x7f9180d41d00 (order_goods_44_0)
T@6    : 16225:         hash.c:   264:    6: | | | | | >my_hash_first_from_hash_value
T@6    : 16226:         hash.c:   290:    6: | | | | | <my_hash_first_from_hash_value 290
T@6    : 16227:  rpl_tblmap.cc:   136:    5: | | | | | info: tid 308820498 -> table 0x7f9180d41d00 (order_goods_44_0)
T@6    : 16228:  rpl_tblmap.cc:   137:    5: | | | | <table_mapping::set_table(ulong,TABLE*) 137

...

T@6    : 16245:  rpl_tblmap.cc:    62:    5: | | | | >table_mapping::get_table(ulong)
T@6    : 16246:  rpl_tblmap.cc:    63:    5: | | | | | enter: table_id: 4603787794
T@6    : 16247:         hash.c:   264:    6: | | | | | >my_hash_first_from_hash_value
T@6    : 16248:         hash.c:   290:    6: | | | | | <my_hash_first_from_hash_value 290
T@6    : 16249:  rpl_tblmap.cc:    73:    5: | | | | | info: tid 4603787794 is not mapped!
T@6    : 16250:  rpl_tblmap.cc:    74:    5: | | | | <table_mapping::get_table(ulong) 74

```

再观察set_table和get_table函数

```
int table_mapping::set_table(ulong table_id, TABLE* table)
{
  DBUG_ENTER("table_mapping::set_table(ulong,TABLE*)");
  DBUG_PRINT("enter", ("table_id: %lu  table: 0x%lx (%s)", 
		       table_id, 
		       (long) table, MAYBE_TABLE_NAME(table)));
  entry *e= find_entry(table_id);
  
  ...
  
}

TABLE* table_mapping::get_table(ulong table_id)
{
  DBUG_ENTER("table_mapping::get_table(ulong)");
  DBUG_PRINT("enter", ("table_id: %lu", table_id));
  entry *e= find_entry(table_id);
  if (e) 
  
  ...
}
```

会发现，两者都只是显示了入参table_id，ulonglong类型。所以，我们要继续寻找上一层调用，Rows_log_event::do_apply_event(Relay_log_info*)函数。

> 当然，我们可以通过GDB进行跟踪，但DBUG报告也同样可以通过调用深度，来判断上一层调用。

```
在do_apply_event函数中，两个函数调用给的入参并不一样
const_cast<Relay_log_info*>(rli)->m_table_map.set_table(ptr->table_id, ptr->table);
const_cast<Relay_log_info*>(rli)->m_table_map.get_table(m_table_id);

ptr->table_id的定义
 uint          table_id; /* table id (from binlog) for opened table 
而m_table_id的定义却是
ulong       m_table_id;	/* Table ID */

```

当我们继续往上追溯时，会发现，他们的值来源一致，可是两者的定义不一致，导致了最后，set_table完全没法和get_table函数，形成合理的写入获取关系，也就是说get_table无法获取到正常值。

#### 第五环节：观察数据库的表数量等

首先，我们明确table_id是什么呢，它是table_cache中，与具体的表关联的随机id值(并非存储在数据文件中的固定值,同一个表也可以id不一样)，随着进入cache的次序，逐渐提高。也就是说，有逐渐增加的趋势，并且会写入binlog。

观察MYSQL发现，因为分库分表的原因，共有10000个表，而table cache定义为614。这将导致频繁的换入换出。

### 故障结论

##### 重启复制操作恢复正常的原因

table_id重头开始分配，只要不增加到32位以上，该问题不会出现。

##### 每隔一段时间故障出现的原因

因为表的数量过多，table cache只有614，过一段时间，table_id将突破32位保存范围。

### 故障的处理方法

* 升级版本到5.6或以上，在5.5中该bug未修复
* 简单的修改 uint          table_id; /* table id (from binlog) for opened table */ 的定义为ulong，也可以使得复制正常。
* 将table cache调大，减少在单个实例中分表的个数，都可以降低风险。




